#!/usr/bin/env node

// available commands
var commands = {
  polyline: './cmd/polyline',
  openaddresses: './cmd/oa',
  vertices: './cmd/vertices',
  search: './cmd/search',
  server: './cmd/server',
};

// remove cmd name from args
var cmd = process.argv[2];
process.argv.splice(2, 1);

// run command
if( cmd in commands ){
  require( commands[cmd] );
}

// invalid command
else {
  console.error( '\n' + helpText()  + '\n' );
  process.exit(1);
}

function helpText(){
  return [
    'Usage: interpolate [command] [options]',
    'Note: you will need to pipe data in to the import/conflate commands',
    '',
    ' help                                                                      output usage information',
    ' search [address_db] [street_db] [lat] [lon] [house_number] [street_name]  search database for specified housenumber + street',
    ' polyline [street_db]                                                      import polyline data in to [street_db]',
    ' oa [address_db] [street_db]                                               conflate oa csv file in to [address_db] using [street_db]',
    ' vertices [address_db] [street_db]                                         compute fractional house numbers for line vertices',
    ' extract [address_db] [street_db] [lat] [lon] [street_name]                extract street address data for debugging purposes',
    ' server [address_db] [street_db]                                           start a web server'
  ].join('\n');
}
